name: Valinta-tulos-service

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'

jobs:
  test-and-build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Europe/Helsinki"

      - name: Build with Maven
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          mvn -B clean package
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: |
            target
          key: ${{ github.sha }}

  deploy-jar-library:
    needs: test-and-build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: restore-build
        with:
          path: |
            target
          key: ${{ github.sha }}

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Deploy jar library
        if: github.ref == 'refs/heads/master'
        shell: bash
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        run: |
          git clone https://github.com/Opetushallitus/ci-tools.git
          source ci-tools/common/setup-tools.sh
          mvn deploy -B -pl fi.vm.sade:scala-group-emailer_2.11 -DskipTests --settings ci-tools/common/maven-settings.xml