name: Valinta-tulos-service

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'

jobs:
  test-and-build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Europe/Helsinki"

      - name: Build with Maven
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          mvn -B clean package
      - uses: actions/cache@v4
        id: restore-build
        with:
          path: |
            target
          key: ${{ github.sha }}

  deploy_to_artifactory:
    runs-on: ubuntu-latest
    needs: test-and-build
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        id: ci-tools
        with:
          path: ci-tools
          key: ${{ github.sha }}

      - name: Deploy to artifactory
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        run: |
          set -euo pipefail
          git clone https://github.com/Opetushallitus/ci-tools.git
          export ARTIFACT_NAME="scala-group-emailer"
          source ci-tools/common/setup-tools.sh
          mvn deploy -DskipTests --settings ci-tools/common/maven-settings.xml